import type { SQLiteDatabase } from 'expo-sqlite';
import * as DocumentPicker from 'expo-document-picker';
import { Directory, File, Paths } from 'expo-file-system';
import * as Sharing from 'expo-sharing';

export type AttachmentOwner='TASK'|'MEMORY';
export interface Attachment{id:string;ownerType:AttachmentOwner;ownerId:string;name:string;mimeType:string;size:number|null;uri:string;createdAt:string;}
export interface StagedAttachment{id:string;name:string;mimeType:string;size:number|null;uri:string;createdAt:string;}
export class AttachmentUploadError extends Error{readonly selectedCount:number;readonly copiedCount:number;readonly persistedCount:number;readonly rolledBackCount:number;readonly cleanupFailures:number;constructor(message:string,status:{selectedCount:number;copiedCount:number;persistedCount:number;rolledBackCount:number;cleanupFailures:number}){super(message);this.name='AttachmentUploadError';this.selectedCount=status.selectedCount;this.copiedCount=status.copiedCount;this.persistedCount=status.persistedCount;this.rolledBackCount=status.rolledBackCount;this.cleanupFailures=status.cleanupFailures;}}
type AttachmentRow={id:string;owner_type:AttachmentOwner;owner_id:string;name:string;mime_type:string;size:number|null;uri:string;created_at:string};
const toAttachment=(row:AttachmentRow):Attachment=>({id:row.id,ownerType:row.owner_type,ownerId:row.owner_id,name:row.name,mimeType:row.mime_type,size:row.size,uri:row.uri,createdAt:row.created_at});
const safeName=(name:string)=>name.replace(/[^a-zA-Z0-9._-]+/gu,'_').slice(0,160)||'file';
const id=()=>`${Date.now()}-${Math.random().toString(36).slice(2,10)}`;
const attachmentDirectory=()=>new Directory(Paths.document,'attachments');
async function ownerExists(db:SQLiteDatabase,ownerType:AttachmentOwner,ownerId:string):Promise<boolean>{const table=ownerType==='TASK'?'tasks':'memories';const row=await db.getFirstAsync<{id:string}>(`SELECT id FROM ${table} WHERE id=? LIMIT 1`,ownerId);return Boolean(row);}
async function deleteFile(uri:string):Promise<void>{const file=new File(uri);if(file.exists)file.delete();}
async function cleanupFiles(uris:string[]):Promise<number>{let failures=0;for(const uri of uris){try{await deleteFile(uri)}catch{failures+=1}}return failures;}
export async function deleteAttachmentFiles(items:Pick<Attachment,'uri'>[]):Promise<number>{return cleanupFiles(items.map(item=>item.uri));}
export async function listAttachments(db:SQLiteDatabase,ownerType:AttachmentOwner,ownerId:string):Promise<Attachment[]>{const rows=await db.getAllAsync<AttachmentRow>('SELECT id,owner_type,owner_id,name,mime_type,size,uri,created_at FROM attachments WHERE owner_type=? AND owner_id=? ORDER BY created_at DESC',ownerType,ownerId);return rows.map(toAttachment);}
export async function stageAttachments():Promise<StagedAttachment[]>{const result=await DocumentPicker.getDocumentAsync({type:'*/*',multiple:true,copyToCacheDirectory:true});if(result.canceled||!result.assets?.length)return [];const directory=attachmentDirectory();directory.create({intermediates:true,idempotent:true});const staged:StagedAttachment[]=[];const copiedUris:string[]=[];try{for(const asset of result.assets){const attachmentId=id();const destination=new File(directory,`${attachmentId}-${safeName(asset.name)}`);const source=new File(asset.uri);source.copy(destination);copiedUris.push(destination.uri);staged.push({id:attachmentId,name:asset.name,mimeType:asset.mimeType??'application/octet-stream',size:asset.size??null,uri:destination.uri,createdAt:new Date().toISOString()});}return staged}catch(error){const cleanupFailures=await cleanupFiles(copiedUris);throw new AttachmentUploadError('Attachment staging failed',{selectedCount:result.assets.length,copiedCount:copiedUris.length,persistedCount:0,rolledBackCount:copiedUris.length-cleanupFailures,cleanupFailures});}}
export async function discardStagedAttachments(items:StagedAttachment[]):Promise<void>{const cleanupFailures=await cleanupFiles(items.map(item=>item.uri));if(cleanupFailures)throw new Error('Attachment cleanup failed');}
export async function finalizeStagedAttachments(db:SQLiteDatabase,ownerType:AttachmentOwner,ownerId:string,items:StagedAttachment[]):Promise<Attachment[]>{if(!items.length)return [];if(!(await ownerExists(db,ownerType,ownerId)))throw new Error('Attachment owner does not exist');let persistedCount=0;try{await db.withTransactionAsync(async()=>{for(const item of items){await db.runAsync('INSERT INTO attachments (id,owner_type,owner_id,name,mime_type,size,uri,created_at) VALUES (?,?,?,?,?,?,?,?)',item.id,ownerType,ownerId,item.name,item.mimeType,item.size,item.uri,item.createdAt);persistedCount+=1;}});return items.map(item=>({...item,ownerType,ownerId}));}catch(error){const cleanupFailures=await cleanupFiles(items.map(item=>item.uri));throw new AttachmentUploadError('Attachment database insertion failed',{selectedCount:items.length,copiedCount:items.length,persistedCount,rolledBackCount:items.length,cleanupFailures});}}
export async function addAttachments(db:SQLiteDatabase,ownerType:AttachmentOwner,ownerId:string):Promise<Attachment[]>{if(!(await ownerExists(db,ownerType,ownerId)))throw new Error('Attachment owner does not exist');const staged=await stageAttachments();if(!staged.length)return [];return finalizeStagedAttachments(db,ownerType,ownerId,staged)}
export async function removeAttachment(db:SQLiteDatabase,attachment:Attachment):Promise<boolean>{const result=await db.runAsync('DELETE FROM attachments WHERE id=?',attachment.id);if(result.changes>0){try{await deleteFile(attachment.uri)}catch{}return true}return false;}
export async function removeAttachmentsForOwner(db:SQLiteDatabase,ownerType:AttachmentOwner,ownerId:string):Promise<number>{const items=await listAttachments(db,ownerType,ownerId);if(!items.length)return 0;let changes=0;await db.withTransactionAsync(async()=>{const result=await db.runAsync('DELETE FROM attachments WHERE owner_type=? AND owner_id=?',ownerType,ownerId);changes=result.changes;});await deleteAttachmentFiles(items);return changes;}
export function getAvailableAttachmentStorage():number{return Paths.availableDiskSpace;}
export async function shareAttachment(attachment:Attachment):Promise<void>{if(!(await Sharing.isAvailableAsync()))throw new Error('File sharing is unavailable on this device');await Sharing.shareAsync(attachment.uri,{mimeType:attachment.mimeType,dialogTitle:attachment.name});}
