import type { SQLiteDatabase } from 'expo-sqlite';
import { strFromU8, strToU8, unzipSync, zipSync } from 'fflate';
import { File } from 'expo-file-system';
import { readSQLiteBackupData } from '../backup/sqlite-reader';
export const BACKUP_ARCHIVE_FORMAT='offline-memory-backup-archive' as const;
export const BACKUP_ARCHIVE_VERSION=2 as const;
type AttachmentOwner='TASK'|'MEMORY';
export interface BackupArchiveAttachment{id:string;ownerType:AttachmentOwner;ownerId:string;name:string;mimeType:string;size:number|null;createdAt:string}
export interface BackupArchiveManifest{format:typeof BACKUP_ARCHIVE_FORMAT;version:typeof BACKUP_ARCHIVE_VERSION;createdAt:string;databaseFile:string;data:Record<string,unknown>;attachments:BackupArchiveAttachment[]}
export interface BackupArchiveResult{bytes:Uint8Array;createdAt:string;attachmentCount:number}
type AttachmentRow={id:string;owner_type:AttachmentOwner;owner_id:string;name:string;mime_type:string;size:number|null;uri:string;created_at:string};
export function base64ToBytes(value:string):Uint8Array{const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';const clean=value.replace(/\s/gu,'');if(clean.length%4!==0||/[^A-Za-z0-9+/=]/u.test(clean))throw new Error('Invalid attachment data');const padding=clean.endsWith('==')?2:clean.endsWith('=')?1:0;const output=new Uint8Array(clean.length/4*3-padding);let outputIndex=0;for(let index=0;index<clean.length;index+=4){const a=alphabet.indexOf(clean[index]!);const b=alphabet.indexOf(clean[index+1]!);const c=clean[index+2]==='='?0:alphabet.indexOf(clean[index+2]!);const d=clean[index+3]==='='?0:alphabet.indexOf(clean[index+3]!);if(a<0||b<0||c<0||d<0)throw new Error('Invalid attachment data');const chunk=(a<<18)|(b<<12)|(c<<6)|d;if(outputIndex<output.length)output[outputIndex++]=(chunk>>>16)&255;if(outputIndex<output.length)output[outputIndex++]=(chunk>>>8)&255;if(outputIndex<output.length)output[outputIndex++]=chunk&255}return output}
export function bytesToBase64(value:Uint8Array):string{const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';let output='';for(let index=0;index<value.length;index+=3){const a=value[index]!;const hasB=index+1<value.length;const hasC=index+2<value.length;const b=hasB?value[index+1]!:0;const c=hasC?value[index+2]!:0;const chunk=(a<<16)|(b<<8)|c;output+=alphabet[(chunk>>>18)&63]!;output+=alphabet[(chunk>>>12)&63]!;output+=hasB?alphabet[(chunk>>>6)&63]:'=';output+=hasC?alphabet[chunk&63]:'='}return output}
function manifestJson(manifest:BackupArchiveManifest):Uint8Array{return strToU8(JSON.stringify(manifest))}
export async function createBackupArchive(db:SQLiteDatabase,createdAt=new Date().toISOString()):Promise<BackupArchiveResult>{if(!Number.isFinite(Date.parse(createdAt)))throw new Error('Backup createdAt must be a valid ISO date');const data=await readSQLiteBackupData(db) as unknown as Record<string,unknown>;const databaseBytes=await db.serializeAsync('main');const attachments=await db.getAllAsync<AttachmentRow>('SELECT id,owner_type,owner_id,name,mime_type,size,uri,created_at FROM attachments ORDER BY id ASC');const taskRows=Array.isArray(data.tasks)?data.tasks as Array<Record<string,unknown>>:[];const memoryRows=Array.isArray(data.memories)?data.memories as Array<Record<string,unknown>>:[];const taskIds=new Set(taskRows.map(row=>String(row.id)));const memoryIds=new Set(memoryRows.map(row=>String(row.id)));const files:Record<string,Uint8Array|[Uint8Array,{level:0|6}]>={'database.sqlite':[databaseBytes,{level:0}]};const metadata:BackupArchiveAttachment[]=[];for(const attachment of attachments){if(attachment.owner_type==='TASK'?!taskIds.has(attachment.owner_id):!memoryIds.has(attachment.owner_id))throw new Error(`Attachment references missing ${attachment.owner_type.toLowerCase()}: ${attachment.owner_id}`);const bytes=base64ToBytes(await new File(attachment.uri).base64());if(attachment.size!==null&&bytes.byteLength!==attachment.size)throw new Error(`Attachment size mismatch: ${attachment.id}`);metadata.push({id:attachment.id,ownerType:attachment.owner_type,ownerId:attachment.owner_id,name:attachment.name,mimeType:attachment.mime_type,size:attachment.size,createdAt:attachment.created_at});files[`attachments/${attachment.id}`]=[bytes,{level:0}]}const manifest:BackupArchiveManifest={format:BACKUP_ARCHIVE_FORMAT,version:BACKUP_ARCHIVE_VERSION,createdAt,databaseFile:'database.sqlite',data,attachments:metadata};files['manifest.json']=[manifestJson(manifest),{level:6}];return{bytes:zipSync(files),createdAt,attachmentCount:metadata.length}}
export function parseBackupArchive(bytes:Uint8Array):BackupArchiveManifest{const files=unzipSync(bytes);const manifestBytes=files['manifest.json'];if(!manifestBytes)throw new Error('Backup archive manifest is missing');let value:unknown;try{value=JSON.parse(strFromU8(manifestBytes))}catch{throw new Error('Backup archive manifest is invalid')}if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Backup archive manifest must be an object');const manifest=value as Partial<BackupArchiveManifest>;if(manifest.format!==BACKUP_ARCHIVE_FORMAT)throw new Error('Unsupported backup archive format');if(manifest.version!==BACKUP_ARCHIVE_VERSION)throw new Error('Unsupported backup archive version');if(typeof manifest.createdAt!=='string'||!Number.isFinite(Date.parse(manifest.createdAt)))throw new Error('Backup archive createdAt must be valid');if(manifest.databaseFile!=='database.sqlite'||!files['database.sqlite']?.byteLength)throw new Error('Backup archive database is missing');if(!manifest.data||typeof manifest.data!=='object'||Array.isArray(manifest.data))throw new Error('Backup archive data must be an object');if(!Array.isArray(manifest.attachments))throw new Error('Backup archive attachments must be an array');const seen=new Set<string>();for(const item of manifest.attachments){if(!item||typeof item!=='object'||Array.isArray(item))throw new Error('Invalid backup attachment metadata');const attachment=item as BackupArchiveAttachment;if(!/^[A-Za-z0-9._-]{1,200}$/u.test(attachment.id)||seen.has(attachment.id))throw new Error(`Invalid or duplicate backup attachment id: ${String(attachment.id)}`);seen.add(attachment.id);if(attachment.ownerType!=='TASK'&&attachment.ownerType!=='MEMORY')throw new Error('Invalid backup attachment owner type');if(!attachment.ownerId||!attachment.name||!attachment.mimeType||typeof attachment.createdAt!=='string')throw new Error('Invalid backup attachment metadata');if(attachment.size!==null&&(!Number.isInteger(attachment.size)||attachment.size<0))throw new Error('Invalid backup attachment size');const file=files[`attachments/${attachment.id}`];if(!file)throw new Error(`Backup attachment data is missing: ${attachment.id}`);if(attachment.size!==null&&file.byteLength!==attachment.size)throw new Error(`Backup attachment size mismatch: ${attachment.id}`)}return manifest as BackupArchiveManifest}
export function encodeBackupArchive(bytes:Uint8Array):string{return bytesToBase64(bytes)}
