import type { SQLiteDatabase } from 'expo-sqlite';
import type { CreateMemoryInput, Memory, UpdateMemoryInput } from '../types/memory-model';
import { deleteAttachmentFiles, listAttachments } from './attachment-service';

const now = () => new Date().toISOString();
const makeId = () => `${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;

function normalizeText(value: string): string { return value.normalize('NFKC').trim().toLocaleLowerCase(); }
function normalizeTags(tags: string[] | undefined): string[] { return [...new Set((tags ?? []).map((tag) => normalizeText(tag)).filter(Boolean))].slice(0, 30); }
function rowToMemory(row: Record<string, unknown>): Memory {
  let tags: string[] = [];
  try { const parsed = JSON.parse(String(row.tags_json ?? '[]')); if (Array.isArray(parsed)) tags = parsed.filter((value): value is string => typeof value === 'string'); } catch { tags = []; }
  return { id: String(row.id), title: row.title == null ? null : String(row.title), content: String(row.content), kind: row.kind as Memory['kind'], source: row.source as Memory['source'], tags, importance: Number(row.importance), archived: Number(row.archived) === 1, createdAt: String(row.created_at), updatedAt: String(row.updated_at), lastAccessedAt: row.last_accessed_at == null ? null : String(row.last_accessed_at) };
}
const SELECT = `SELECT id, title, content, kind, source, tags_json, importance, archived, created_at, updated_at, last_accessed_at FROM memories`;
const LIVE = 'deleted_at IS NULL';
export type TrashedMemory = Memory & { deletedAt: string };
export async function createMemory(db: SQLiteDatabase, input: CreateMemoryInput): Promise<Memory> { const content = input.content.trim(); if (!content) throw new Error('Memory content is required'); const importance = Math.min(5, Math.max(1, Math.round(input.importance ?? 3))); const timestamp = now(); const id = makeId(); await db.runAsync(`INSERT INTO memories (id, title, content, kind, source, tags_json, importance, archived, created_at, updated_at, last_accessed_at) VALUES (?, ?, ?, ?, ?, ?, ?, 0, ?, ?, NULL)`, id, input.title?.trim() || null, content, input.kind ?? 'NOTE', input.source ?? 'USER', JSON.stringify(normalizeTags(input.tags)), importance, timestamp, timestamp); return (await getMemory(db, id))!; }
export async function getMemory(db: SQLiteDatabase, id: string): Promise<Memory | null> { const row = await db.getFirstAsync<Record<string, unknown>>(`${SELECT} WHERE id = ? AND ${LIVE} LIMIT 1`, id); return row ? rowToMemory(row) : null; }
export async function listMemories(db: SQLiteDatabase, includeArchived = false, limit = 100): Promise<Memory[]> { const safeLimit = Math.max(1, Math.min(Math.floor(limit), 500)); const rows = await db.getAllAsync<Record<string, unknown>>(`${SELECT} WHERE archived = ? AND ${LIVE} ORDER BY importance DESC, updated_at DESC LIMIT ?`, includeArchived ? 1 : 0, safeLimit); return rows.map(rowToMemory); }
export async function listAllMemories(db: SQLiteDatabase): Promise<Memory[]> { const rows = await db.getAllAsync<Record<string, unknown>>(`${SELECT} WHERE ${LIVE} ORDER BY created_at ASC`); return rows.map(rowToMemory); }
export async function listTrashedMemories(db: SQLiteDatabase): Promise<TrashedMemory[]> { const rows = await db.getAllAsync<Record<string, unknown>>(`SELECT id, title, content, kind, source, tags_json, importance, archived, created_at, updated_at, last_accessed_at, deleted_at FROM memories WHERE deleted_at IS NOT NULL ORDER BY deleted_at DESC`); return rows.map((row) => ({ ...rowToMemory(row), deletedAt: String(row.deleted_at) })); }
export async function restoreMemory(db: SQLiteDatabase, id: string): Promise<boolean> { const r = await db.runAsync('UPDATE memories SET deleted_at = NULL, updated_at = ? WHERE id = ? AND deleted_at IS NOT NULL', now(), id); return (r.changes ?? 0) > 0; }
export async function purgeMemory(db: SQLiteDatabase, id: string): Promise<boolean> { const row = await db.getFirstAsync<{ id: string }>('SELECT id FROM memories WHERE id = ? LIMIT 1', id); if (!row) return false; const attachments = await listAttachments(db, 'MEMORY', id); await db.withTransactionAsync(async()=>{ await db.runAsync('DELETE FROM attachments WHERE owner_type=? AND owner_id=?','MEMORY',id); await db.runAsync("DELETE FROM relations WHERE (from_type='MEMORY' AND from_id=?) OR (to_type='MEMORY' AND to_id=?)",id,id); await db.runAsync('DELETE FROM memories WHERE id=?',id); }); await deleteAttachmentFiles(attachments); return true; }
export async function purgeExpiredMemories(db: SQLiteDatabase, before: string): Promise<number> { const rows = await db.getAllAsync<{ id: string }>('SELECT id FROM memories WHERE deleted_at IS NOT NULL AND deleted_at < ?', before); for (const row of rows) await purgeMemory(db, row.id).catch(() => {}); return rows.length; }
export async function emptyMemoryTrash(db: SQLiteDatabase): Promise<number> { const rows = await db.getAllAsync<{ id: string }>('SELECT id FROM memories WHERE deleted_at IS NOT NULL'); for (const row of rows) await purgeMemory(db, row.id).catch(() => {}); return rows.length; }
export async function updateMemory(db: SQLiteDatabase, id: string, input: UpdateMemoryInput): Promise<Memory | null> { const current = await getMemory(db, id); if (!current) return null; const content = input.content === undefined ? current.content : input.content.trim(); if (!content) throw new Error('Memory content is required'); await db.runAsync(`UPDATE memories SET title = ?, content = ?, kind = ?, tags_json = ?, importance = ?, archived = ?, updated_at = ? WHERE id = ?`, input.title === undefined ? current.title : input.title?.trim() || null, content, input.kind ?? current.kind, JSON.stringify(normalizeTags(input.tags ?? current.tags)), Math.min(5, Math.max(1, Math.round(input.importance ?? current.importance))), input.archived === undefined ? Number(current.archived) : Number(input.archived), now(), id); return getMemory(db, id); }
export async function archiveMemory(db: SQLiteDatabase, id: string): Promise<Memory | null> { return updateMemory(db, id, { archived: true }); }
// Soft delete → the trash. `purgeMemory` does the real removal.
export async function deleteMemory(db: SQLiteDatabase, id: string): Promise<boolean> { const ts = now(); const r = await db.runAsync('UPDATE memories SET deleted_at = ?, updated_at = ? WHERE id = ? AND deleted_at IS NULL', ts, ts, id); return (r.changes ?? 0) > 0; }
export async function touchMemory(db: SQLiteDatabase, id: string): Promise<void> { await db.runAsync('UPDATE memories SET last_accessed_at = ?, updated_at = updated_at WHERE id = ?', now(), id); }
function scoreMemory(memory: Memory, terms: string[], phrase: string): number { const title = normalizeText(memory.title ?? ''); const content = normalizeText(memory.content); const tags = memory.tags.map(normalizeText); let score = phrase && `${title} ${content}`.includes(phrase) ? 30 : 0; for (const term of terms) { if (title === term) score += 50; else if (title.includes(term)) score += 20; if (content.includes(term)) score += 10; if (tags.some((tag) => tag === term)) score += 25; else if (tags.some((tag) => tag.includes(term))) score += 8; } return score + Math.max(0, Math.min(5, memory.importance)) * 2 + (memory.lastAccessedAt ? 1 : 0); }
export async function searchMemories(db: SQLiteDatabase, query: string, matchAll = false): Promise<Memory[]> { const normalizedQuery = normalizeText(query); const terms = [...new Set(normalizedQuery.split(/\s+/).filter(Boolean))].slice(0, 8); if (!terms.length) return listMemories(db); const clauses = terms.map(() => '(lower(content) LIKE ? OR lower(COALESCE(title, "")) LIKE ? OR lower(tags_json) LIKE ?)'); const joiner = matchAll ? ' AND ' : ' OR '; const args = terms.flatMap((term) => [`%${term}%`, `%${term}%`, `%${term}%`]); const rows = await db.getAllAsync<Record<string, unknown>>(`${SELECT} WHERE archived = 0 AND ${LIVE} AND (${clauses.join(joiner)})`, ...args); return rows.map(rowToMemory).filter((memory) => { if (!matchAll) return true; const haystack = `${memory.title ?? ''} ${memory.content} ${memory.tags.join(' ')}`.toLocaleLowerCase(); return terms.every((term) => haystack.includes(term)); }).map((memory) => ({ memory, score: scoreMemory(memory, terms, normalizedQuery) })).filter((item) => item.score > 0).sort((a, b) => b.score - a.score || b.memory.updatedAt.localeCompare(a.memory.updatedAt)).map((item) => item.memory); }
