import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(__dirname,'..');
const read=(file:string)=>fs.readFileSync(path.join(root,file),'utf8');
describe('final surgical UI contracts',()=>{
 it('uses the adaptive 600/840 window contract and starts the navigation rail at 600dp',()=>{const theme=read('src/theme/index.ts');const nav=read('src/ui/PrimaryNav.tsx');expect(theme).toContain('compactWindow:600');expect(theme).toContain('mediumWindow:840');expect(theme).toContain('expandedNavigation:840');expect(nav).toContain('const rail = width >= breakpoints.compactWindow;');});
 it('keeps attachment lifecycle cleanup at the task and memory repository boundaries',()=>{expect(read('src/services/task-repository.ts')).toContain("removeAttachmentsForOwner(db, 'TASK', id)");expect(read('src/services/memory-repository.ts')).toContain("removeAttachmentsForOwner(db, 'MEMORY', id)");});
 it('keeps modern local file APIs in attachment and backup services',()=>{expect(read('src/services/attachment-service.ts')).toContain("from 'expo-file-system'");expect(read('src/services/attachment-reconciliation-service.ts')).toContain("from 'expo-file-system'");expect(read('src/backup/file-adapter.ts')).toContain("from 'expo-file-system'");expect(read('src/services/backup-archive-service.ts')).toContain("from 'expo-file-system'");expect(read('src/services/backup-restore-archive-service.ts')).toContain("from 'expo-file-system'");});
 it('keeps destructive restore/delete behind explicit confirmation primitives where audited',()=>{expect(read('app/backup.tsx')).toContain('AppConfirmDialog');expect(read('src/ui/AttachmentPanel.tsx')).toContain('AppConfirmDialog');});
 it('keeps About in the More system group and the product privacy contract visible',()=>{expect(read('app/more.tsx')).toContain("href:'/about'");const about=read('app/about.tsx');expect(about).toContain('Privacy-first');expect(about).toContain('Offline-first');});
 it('keeps diagnostics connected to attachment reconciliation',()=>{expect(read('app/diagnostics.tsx')).toContain('reconcileAttachmentStorage');});
 it('keeps centralized Bangladesh date/time formatters available and timezone-bound',()=>{const source=read('src/i18n/date-time.ts');for(const name of ['formatBangladeshDate','formatBangladeshDateTime','formatBangladeshTime','formatBangladeshWeekdayDate','formatBangladeshMonthYear','formatBangladeshRelativeDate','formatBangladeshNumber'])expect(source).toContain(name);expect(source).toContain('Asia/Dhaka');});
 it('keeps final shared touch-target and reusable UI primitives at the audited contract',()=>{const theme=read('src/theme/index.ts');const surface=read('src/ui/AppSurface.tsx');expect(theme).toContain('minTouchTarget:48');expect(theme).toContain('iconButtonSize:48');for(const name of ['AppCard','AppButton','AppIconButton','AppBadge','AppSectionHeader','AppField','AppSegmentedControl','AppState'])expect(surface).toContain(`export function ${name}`);});
 it('keeps search filters explicit and accessible',()=>{const search=read('app/search.tsx');expect(search).toContain("type SearchFilter='ALL'|'TASKS'|'MEMORIES'");expect(search).toContain('accessibilityRole="tablist"');expect(search).toContain('accessibilityRole="tab"');});
 it('does not expose raw service errors through the audited search/editor surfaces',()=>{for(const file of ['app/search.tsx','app/task-editor.tsx','app/memory-editor.tsx']){const source=read(file);expect(source).not.toContain('error.message');expect(source).not.toContain('Alert.alert');}});
});
