import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(__dirname,'..');
const read=(file:string)=>fs.readFileSync(path.join(root,file),'utf8');
describe('final surgical UI contracts',()=>{
 it('uses the adaptive 600/840 window contract',()=>{const theme=read('src/theme/index.ts');expect(theme).toContain('compactWindow:600');expect(theme).toContain('mediumWindow:840');expect(theme).toContain('expandedNavigation:840');});
 it('keeps atomic attachment lifecycle cleanup at the task and memory repository boundaries',()=>{const task=read('src/services/task-repository.ts');const memory=read('src/services/memory-repository.ts');expect(task).toContain("DELETE FROM attachments WHERE owner_type=? AND owner_id=?");expect(task).toContain("'TASK',id");expect(memory).toContain("DELETE FROM attachments WHERE owner_type=? AND owner_id=?");expect(memory).toContain("'MEMORY',id");});
 it('keeps atomic attachment staging and localized rollback status',()=>{const source=read('src/services/attachment-service.ts');expect(source).toContain('stageAttachments');expect(source).toContain('finalizeStagedAttachments');expect(source).toContain('AttachmentUploadError');expect(source).toContain('cleanupFailures');expect(read('app/task-editor.tsx')).toContain('copy.attachmentHint');expect(read('app/memory-editor.tsx')).toContain('copy.draftHint');});
 it('keeps modern local file APIs in attachment and backup services',()=>{expect(read('src/services/attachment-service.ts')).toContain("from 'expo-file-system'");expect(read('src/services/attachment-reconciliation-service.ts')).toContain("from 'expo-file-system'");expect(read('src/backup/file-adapter.ts')).toContain("from 'expo-file-system'");expect(read('src/services/backup-archive-service.ts')).toContain("from 'expo-file-system'");expect(read('src/services/backup-restore-archive-service.ts')).toContain("from 'expo-file-system'");});
 it('keeps Backup v2 as an attachment-aware archive with a serialized SQLite database',()=>{const source=read('src/services/backup-archive-service.ts');expect(source).toContain('BACKUP_ARCHIVE_VERSION=2');expect(source).toContain("serializeAsync('main')");expect(source).toContain("'database.sqlite'");expect(source).toContain('attachments');expect(read('src/services/backup-restore-archive-service.ts')).toContain('parseBackupArchive');expect(read('src/services/backup-service.ts')).toContain('M7_BACKUP_VERSION');});
 it('keeps destructive restore/delete behind explicit confirmation primitives where audited',()=>{expect(read('app/backup.tsx')).toContain('AppConfirmDialog');expect(read('src/ui/AttachmentPanel.tsx')).toContain('AppConfirmDialog');});
 it('keeps About in the More system group and the product privacy contract visible',()=>{const moreSrc=read('app/more.tsx');expect(moreSrc).toMatch(/href:\s*'\/about'/);expect(moreSrc).toMatch(/href:\s*'\/diagnostics'/);const about=read('app/about.tsx');expect(about).toMatch(/[Pp]rivacy first/);expect(about).toMatch(/pathname:\s*'\/doc'/);const doc=read('app/doc.tsx');expect(doc).toMatch(/DOCS\[/);expect(read('src/content/docs.ts')).toMatch(/Privacy Policy/);});
 it('keeps diagnostics connected to attachment reconciliation',()=>{expect(read('app/diagnostics.tsx')).toContain('reconcileAttachmentStorage');});
 it('keeps centralized Bangladesh date/time formatters available while Home is delegated to HomeScreen',()=>{const source=read('src/i18n/date-time.ts');for(const name of ['formatBangladeshDate','formatBangladeshDateTime','formatBangladeshTime','formatBangladeshWeekdayDate','formatBangladeshMonthYear','formatBangladeshRelativeDate','formatBangladeshNumber'])expect(source).toContain(name);expect(read('app/index.tsx')).toContain("export { default } from '../src/ui/HomeScreen';");});
 it('keeps final shared touch-target primitives at 48dp',()=>{const source=read('src/theme/index.ts');expect(source).toContain('minTouchTarget:48');expect(source).toContain('iconButtonSize:48');expect(read('src/ui/AppSurface.tsx')).toContain('minHeight:layout.minTouchTarget');});
 it('keeps search filters and branded Android notification defaults',()=>{expect(read('app/search.tsx')).toContain("type SearchFilter = 'ALL' | 'TASKS' | 'MEMORIES'");const app=read('app.json');expect(app).toContain('"defaultChannel": "task-reminders"');expect(app).toContain('"color": "#2456C9"');});
});
