import { ActivityIndicator, Pressable, StyleSheet, Text, View, type StyleProp, type TextStyle, type ViewStyle } from 'react-native';
import type { ComponentProps, ReactNode } from 'react';
import { AppIcon } from './AppIcon';
import { control, elevation, layout, radius, spacing, typography } from '../theme';
import { useAppPreferences } from '../app/AppPreferences';

type AppCardProps={children:ReactNode;style?:StyleProp<ViewStyle>;elevated?:boolean};
export function AppCard({children,style,elevated=true}:AppCardProps){const{colors}=useAppPreferences();return <View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border},elevated&&elevation.card,style]}>{children}</View>}

type AppButtonProps={label:string;icon?:ComponentProps<typeof AppIcon>['name'];onPress:()=>void;variant?:'primary'|'secondary'|'danger'|'ghost';loading?:boolean;disabled?:boolean;accessibilityLabel?:string;style?:StyleProp<ViewStyle>};
export function AppButton({label,icon,onPress,variant='primary',loading=false,disabled=false,accessibilityLabel,style}:AppButtonProps){const{colors}=useAppPreferences();const disabledState=disabled||loading;const background=variant==='primary'?colors.primary:variant==='danger'?colors.danger:variant==='secondary'?colors.surfaceMuted:'transparent';const foreground=variant==='primary'||variant==='danger'?colors.onPrimary:colors.primary;return <Pressable accessibilityRole="button" accessibilityLabel={accessibilityLabel??label} accessibilityState={{disabled:disabledState,busy:loading}} disabled={disabledState} onPress={onPress} style={({pressed})=>StyleSheet.flatten([styles.button,{backgroundColor:background,borderColor:variant==='ghost'?'transparent':colors.border,opacity:disabledState?.5:pressed?.82:1},style])}>{loading?<ActivityIndicator color={foreground}/>:icon?<AppIcon name={icon} size={control.iconSize-3} color={foreground}/>:null}{!loading?<Text numberOfLines={2} adjustsFontSizeToFit minimumFontScale={0.82} style={[styles.buttonText,{color:foreground}]}>{label}</Text>:null}</Pressable>}

type AppIconButtonProps={icon:ComponentProps<typeof AppIcon>['name'];onPress:()=>void;label:string;variant?:'neutral'|'primary'|'danger';disabled?:boolean;loading?:boolean;style?:StyleProp<ViewStyle>};
export function AppIconButton({icon,onPress,label,variant='neutral',disabled=false,loading=false,style}:AppIconButtonProps){const{colors}=useAppPreferences();const color=variant==='danger'?colors.danger:variant==='primary'?colors.primary:colors.textSecondary;const background=variant==='primary'?colors.surfaceMuted:colors.surface;return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{disabled:disabled||loading,busy:loading}} disabled={disabled||loading} onPress={onPress} style={({pressed})=>[styles.iconButton,{backgroundColor:background,borderColor:colors.border,opacity:disabled||loading?.5:pressed?.78:1},style]}>{loading?<ActivityIndicator size="small" color={color}/>:<AppIcon name={icon} size={control.iconSize-1} color={color}/>}</Pressable>}

type AppBadgeProps={label:string;tone?:'primary'|'success'|'warning'|'danger'|'neutral';style?:StyleProp<TextStyle>};
export function AppBadge({label,tone='neutral',style}:AppBadgeProps){const{colors}=useAppPreferences();const palette=tone==='primary'?{bg:colors.surfaceMuted,fg:colors.primary}:tone==='success'?{bg:colors.surfaceMuted,fg:colors.success}:tone==='warning'?{bg:colors.surfaceMuted,fg:colors.warning}:tone==='danger'?{bg:colors.surfaceMuted,fg:colors.danger}:{bg:colors.surfaceMuted,fg:colors.textSecondary};return <View style={[styles.badge,{backgroundColor:palette.bg}]}><Text numberOfLines={1} style={[styles.badgeText,{color:palette.fg},style]}>{label}</Text></View>}

type AppSectionHeaderProps={title:string;description?:string;actionLabel?:string;onAction?:()=>void};
export function AppSectionHeader({title,description,actionLabel,onAction}:AppSectionHeaderProps){const{colors}=useAppPreferences();return <View style={styles.sectionHeader}><View style={styles.sectionCopy}><Text style={[styles.sectionTitle,{color:colors.textPrimary}]}>{title}</Text>{description?<Text style={[styles.sectionDescription,{color:colors.textSecondary}]}>{description}</Text>:null}</View>{actionLabel&&onAction?<Pressable accessibilityRole="button" accessibilityLabel={actionLabel} onPress={onAction} style={({pressed})=>[styles.sectionAction,pressed&&styles.pressed]}><Text style={[styles.sectionActionText,{color:colors.primary}]}>{actionLabel}</Text><AppIcon name="chevron-right" size={17} color={colors.primary}/></Pressable>:null}</View>}

type AppStateProps={title:string;description?:string;icon?:ComponentProps<typeof AppIcon>['name'];loading?:boolean;actionLabel?:string;onAction?:()=>void};
export function AppState({title,description,icon='information-outline',loading=false,actionLabel,onAction}:AppStateProps){const{colors}=useAppPreferences();return <View style={styles.state} accessibilityRole={loading?'progressbar':undefined}>{loading?<ActivityIndicator size="large" color={colors.primary}/>:<View style={[styles.stateIcon,{backgroundColor:colors.surfaceMuted}]}><AppIcon name={icon} size={28} color={colors.primary}/></View>}<Text style={[styles.stateTitle,{color:colors.textPrimary}]}>{title}</Text>{description?<Text style={[styles.stateDescription,{color:colors.textSecondary}]}>{description}</Text>:null}{actionLabel&&onAction?<AppButton label={actionLabel} onPress={onAction} variant="secondary"/>:null}</View>}

const styles=StyleSheet.create({card:{borderWidth:1,borderRadius:radius.lg,padding:spacing.md},button:{minHeight:control.buttonHeight,minWidth:layout.minTouchTarget,maxWidth:'100%',borderWidth:1,borderRadius:radius.md,paddingHorizontal:spacing.md,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:spacing.sm},buttonText:{...typography.bodySmall,fontWeight:'800',flexShrink:1,textAlign:'center'},iconButton:{width:layout.iconButtonSize,height:layout.iconButtonSize,borderWidth:1,borderRadius:radius.md,alignItems:'center',justifyContent:'center'},badge:{alignSelf:'flex-start',minHeight:28,paddingHorizontal:spacing.sm,borderRadius:radius.pill,alignItems:'center',justifyContent:'center'},badgeText:{fontSize:11,lineHeight:15,fontWeight:'900'},sectionHeader:{minHeight:44,flexDirection:'row',alignItems:'center',gap:spacing.sm},sectionCopy:{flex:1,minWidth:0},sectionTitle:{fontSize:17,lineHeight:23,fontWeight:'900'},sectionDescription:{fontSize:12,lineHeight:18,marginTop:2},sectionAction:{minHeight:44,paddingHorizontal:spacing.xs,flexDirection:'row',alignItems:'center',gap:2},sectionActionText:{fontSize:12,fontWeight:'900'},state:{alignItems:'center',justifyContent:'center',paddingHorizontal:spacing.lg,paddingVertical:spacing.xl,gap:spacing.sm},stateIcon:{width:spacing.lgPlus+spacing.smd,height:spacing.lgPlus+spacing.smd,borderRadius:radius.lg,alignItems:'center',justifyContent:'center'},stateTitle:{fontSize:18,lineHeight:24,fontWeight:'900',textAlign:'center'},stateDescription:{...typography.bodySmall,maxWidth:420,textAlign:'center'},pressed:{opacity:.78}});
