import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { useSQLiteContext } from 'expo-sqlite';
import { AppCard, AppState } from './AppSurface';
import { AppIcon } from './AppIcon';
import { useAppPreferences } from '../app/AppPreferences';
import { addAttachments, listAttachments, removeAttachment, shareAttachment, type Attachment, type AttachmentOwner } from '../services/attachment-service';
import { spacing, type ThemeColors } from '../theme';

function iconFor(mime:string){if(mime.startsWith('image/'))return 'file-image-outline' as const;if(mime.startsWith('video/'))return 'file-video-outline' as const;if(mime.startsWith('audio/'))return 'file-music-outline' as const;if(mime.includes('pdf'))return 'file-pdf-box' as const;return 'file-outline' as const;}
function typeLabel(mime:string,bn:boolean){if(mime.startsWith('image/'))return bn?'ছবি':'Image';if(mime.startsWith('video/'))return bn?'ভিডিও':'Video';if(mime.startsWith('audio/'))return bn?'অডিও':'Audio';if(mime.includes('pdf'))return 'PDF';return bn?'ডকুমেন্ট':'Document';}
function formatSize(size:number|null,bn:boolean){if(size===null)return bn?'আকার অজানা':'Size unknown';if(size<1024)return `${size} B`;if(size<1024*1024)return `${(size/1024).toFixed(1)} KB`;return `${(size/1024/1024).toFixed(1)} MB`;}
function formatAddedAt(value:string,bn:boolean){const date=new Date(value);if(Number.isNaN(date.getTime()))return '';return new Intl.DateTimeFormat(bn?'bn-BD':'en-BD',{dateStyle:'medium',timeStyle:'short',hour12:false}).format(date);}

export function AttachmentPanel({ownerType,ownerId}:{ownerType:AttachmentOwner;ownerId:string}){
 const db=useSQLiteContext();const{colors,language}=useAppPreferences();const bn=language==='bn';const styles=useMemo(()=>makeStyles(colors),[colors]);const[items,setItems]=useState<Attachment[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{try{const next=await listAttachments(db,ownerType,ownerId);setItems(next);setError(null)}catch{setError(bn?'ফাইলগুলো লোড করা যায়নি':'Unable to load attachments')}},[bn,db,ownerId,ownerType]);
 useEffect(()=>{let cancelled=false;void listAttachments(db,ownerType,ownerId).then(next=>{if(!cancelled){setItems(next);setError(null)}}).catch(()=>{if(!cancelled)setError(bn?'ফাইলগুলো লোড করা যায়নি':'Unable to load attachments')});return()=>{cancelled=true}},[bn,db,ownerId,ownerType]);
 const add=async()=>{if(busy)return;setBusy(true);setError(null);try{const added=await addAttachments(db,ownerType,ownerId);if(added.length)setItems(current=>[...added,...current])}catch{setError(bn?'ফাইল যোগ করা যায়নি':'Unable to add files')}finally{setBusy(false)}};
 const remove=async(item:Attachment)=>{setBusy(true);setError(null);try{if(await removeAttachment(db,item))setItems(current=>current.filter(value=>value.id!==item.id))}catch{setError(bn?'ফাইলটি মুছে ফেলা যায়নি':'Unable to remove file')}finally{setBusy(false)}};
 const confirmRemove=(item:Attachment)=>Alert.alert(bn?'ফাইল মুছবেন?':'Remove file?',item.name,[{text:bn?'বাতিল':'Cancel',style:'cancel'},{text:bn?'মুছুন':'Remove',style:'destructive',onPress:()=>void remove(item)}]);
 return <View style={styles.wrap}><View style={styles.heading}><View style={styles.headingCopy}><View style={styles.titleLine}><Text style={styles.title}>{bn?'ডকুমেন্ট ও ফাইল':'Documents & files'}</Text>{items.length>0?<View style={styles.count}><Text style={styles.countText}>{items.length}</Text></View>:null}</View><Text style={styles.subtitle}>{bn?'ছবি, ভিডিও, PDF এবং যেকোনো ফাইল স্থানীয়ভাবে রাখুন।':'Keep images, videos, PDFs and any file locally.'}</Text></View><Pressable disabled={busy} onPress={()=>void add()} accessibilityRole="button" accessibilityLabel={bn?'ফাইল যোগ করুন':'Add files'} style={({pressed})=>[styles.addButton,busy&&styles.disabled,pressed&&styles.pressed]}>{busy?<ActivityIndicator color={colors.onPrimary}/>:<><AppIcon name="paperclip" size={18} color={colors.onPrimary}/><Text style={styles.addText}>{bn?'ফাইল যোগ':'Add files'}</Text></>}</Pressable></View>{error?<AppState title={bn?'ফাইল সমস্যা':'File problem'} description={error} icon="alert-circle-outline" actionLabel={bn?'আবার চেষ্টা':'Retry'} onAction={()=>void load()}/>:null}{!error&&items.length===0?<AppCard elevated={false} style={styles.empty}><View style={styles.emptyIcon}><AppIcon name="file-multiple-outline" size={26} color={colors.primary}/></View><Text style={styles.emptyTitle}>{bn?'এখনও কোনো ফাইল নেই':'No files yet'}</Text><Text style={styles.emptyText}>{bn?'ফাইল যোগ করুন; এটি এই ডিভাইসেই সংরক্ষিত থাকবে।':'Add files; they are stored on this device.'}</Text></AppCard>:null}{items.map(item=><AppCard key={item.id} style={styles.item}><View style={styles.fileIcon}>{item.mimeType.startsWith('image/')?<Image source={{uri:item.uri}} style={styles.thumb}/>:<AppIcon name={iconFor(item.mimeType)} size={23} color={colors.primary}/>}</View><View style={styles.fileCopy}><Text numberOfLines={2} style={styles.fileName}>{item.name}</Text><Text style={styles.meta}>{typeLabel(item.mimeType,bn)} · {formatSize(item.size,bn)}</Text><Text numberOfLines={1} style={styles.date}>{formatAddedAt(item.createdAt,bn)}</Text></View><Pressable disabled={busy} onPress={()=>void shareAttachment(item).catch(()=>Alert.alert(bn?'ফাইল শেয়ার করা যায়নি':'Unable to share file'))} accessibilityRole="button" accessibilityLabel={`${bn?'শেয়ার':'Share'} ${item.name}`} style={({pressed})=>[styles.iconButton,busy&&styles.disabled,pressed&&styles.pressed]}><AppIcon name="share-variant-outline" size={19} color={colors.primary}/></Pressable><Pressable disabled={busy} onPress={()=>confirmRemove(item)} accessibilityRole="button" accessibilityLabel={`${bn?'মুছুন':'Remove'} ${item.name}`} style={({pressed})=>[styles.iconButton,busy&&styles.disabled,pressed&&styles.pressed]}><AppIcon name="delete-outline" size={19} color={colors.danger}/></Pressable></AppCard>)}</View>;
}
function makeStyles(colors:ThemeColors){return StyleSheet.create({wrap:{marginTop:spacing.lg,gap:spacing.sm},heading:{flexDirection:'row',alignItems:'center',gap:spacing.sm},headingCopy:{flex:1,minWidth:0},titleLine:{flexDirection:'row',alignItems:'center',gap:6},title:{color:colors.textPrimary,fontSize:18,fontWeight:'900'},count:{minWidth:24,height:24,borderRadius:12,paddingHorizontal:7,backgroundColor:colors.surfaceMuted,alignItems:'center',justifyContent:'center'},countText:{color:colors.primary,fontSize:11,fontWeight:'900'},subtitle:{color:colors.textSecondary,fontSize:12,lineHeight:18,marginTop:3},addButton:{minHeight:44,borderRadius:13,backgroundColor:colors.primary,paddingHorizontal:spacing.sm,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:4},addText:{color:colors.onPrimary,fontWeight:'800'},item:{padding:spacing.sm,flexDirection:'row',alignItems:'center',gap:spacing.sm},fileIcon:{width:50,height:50,borderRadius:14,backgroundColor:colors.surfaceMuted,alignItems:'center',justifyContent:'center',overflow:'hidden'},thumb:{width:50,height:50},fileCopy:{flex:1,minWidth:0},fileName:{color:colors.textPrimary,fontSize:13,fontWeight:'800'},meta:{color:colors.textSecondary,fontSize:10,fontWeight:'700',marginTop:3},date:{color:colors.textMuted,fontSize:9,marginTop:2},iconButton:{width:42,height:42,borderRadius:12,alignItems:'center',justifyContent:'center',backgroundColor:colors.surfaceMuted},empty:{alignItems:'center',justifyContent:'center',padding:spacing.lg},emptyIcon:{width:54,height:54,borderRadius:17,backgroundColor:colors.surfaceMuted,alignItems:'center',justifyContent:'center'},emptyTitle:{color:colors.textPrimary,fontWeight:'900',marginTop:8},emptyText:{color:colors.textSecondary,fontSize:12,textAlign:'center',marginTop:3,lineHeight:18},disabled:{opacity:.5},pressed:{opacity:.78}})}
