import { useMemo } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { useAppPreferences } from '../src/app/AppPreferences';
import { AppIcon } from '../src/ui/AppIcon';
import { AppIconButton } from '../src/ui/AppSurface';
import { layout, radius, spacing, typography, type ThemeColors } from '../src/theme';

export default function AboutScreen(){
 const {colors,language}=useAppPreferences(); const bn=language==='bn'; const styles=useMemo(()=>makeStyles(colors),[colors]);
 const copy=bn?{back:'আরও',eyebrow:'OFFLINE MEMORY',title:'আমাদের সম্পর্কে',tagline:'ব্যক্তিগত স্মৃতি ও কাজ—আপনার ডিভাইসেই।',privacy:'Privacy-first · Offline-first',privacyText:'মূল টাস্ক, মেমোরি, সার্চ, পরিকল্পনা, NLP, রিমাইন্ডার এবং ব্যাকআপ লোকাল ডিভাইসে কাজ করে। আপনার ডেটা কোনো সার্ভারে পাঠানো হয় না, যদি না আপনি নিজে ব্যাকআপ শেয়ার করেন।',features:'মূল বৈশিষ্ট্য',items:['বাংলা ও English','Light ও Dark theme','লোকাল SQLite storage','লোকাল NLP ও Assistant','লোকাল reminders','Attachment-aware backup','ছবি, ভিডিও, PDF ও অন্যান্য ফাইল'],version:'Version',architecture:'Architecture',architectureText:'UI → Application Services → Local NLP/Assistant → Repository → SQLite → Notifications',license:'Offline Memory is a private, offline-first productivity application.','done':'সম্পন্ন'}:{back:'More',eyebrow:'OFFLINE MEMORY',title:'About',tagline:'Personal memory and work—kept on your device.',privacy:'Privacy-first · Offline-first',privacyText:'Core tasks, memories, search, planning, NLP, reminders and backups operate locally. Your data is not sent to a server unless you explicitly share a backup.',features:'Core capabilities',items:['Bangla and English','Light and Dark themes','Local SQLite storage','Local NLP and Assistant','Local reminders','Attachment-aware backups','Images, videos, PDFs and other files'],version:'Version',architecture:'Architecture',architectureText:'UI → Application Services → Local NLP/Assistant → Repository → SQLite → Notifications',license:'Offline Memory is a private, offline-first productivity application.','done':'Done'};
 return <ScrollView style={styles.container} contentContainerStyle={styles.content}><View style={styles.header}><AppIconButton icon="arrow-left" label={copy.back} variant="neutral" onPress={()=>router.back()}/><View style={styles.brand}><View style={styles.brandIcon}><AppIcon name="brain" size={30} color={colors.onPrimary}/></View><View style={styles.brandCopy}><Text style={styles.eyebrow}>{copy.eyebrow}</Text><Text style={styles.title}>{copy.title}</Text></View></View><Text style={styles.tagline}>{copy.tagline}</Text><View style={styles.privacy}><AppIcon name="shield-lock-outline" size={20} color={colors.success}/><View style={styles.privacyCopy}><Text style={styles.privacyTitle}>{copy.privacy}</Text><Text style={styles.privacyText}>{copy.privacyText}</Text></View></View></View><View style={styles.card}><Text style={styles.section}>{copy.features}</Text>{copy.items.map(item=><View key={item} style={styles.row}><AppIcon name="check-circle-outline" size={18} color={colors.success}/><Text style={styles.rowText}>{item}</Text></View>)}</View><View style={styles.card}><Text style={styles.section}>{copy.architecture}</Text><Text style={styles.architecture}>{copy.architectureText}</Text></View><Text style={styles.version}>{copy.version} 0.1.0 · {copy.done}</Text><Text style={styles.license}>{copy.license}</Text></ScrollView>;
}
function makeStyles(colors:ThemeColors){return StyleSheet.create({container:{flex:1,backgroundColor:colors.background},content:{width:'100%',maxWidth:layout.contentMaxWidth,alignSelf:'center',paddingHorizontal:spacing.lg,paddingTop:spacing.md,paddingBottom:spacing.xxl},header:{paddingTop:spacing.sm},brand:{flexDirection:'row',alignItems:'center',gap:spacing.md,marginTop:spacing.lg},brandIcon:{width:60,height:60,borderRadius:20,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},brandCopy:{flex:1,minWidth:0},eyebrow:{color:colors.primary,fontSize:typography.label.fontSize,fontWeight:'900',letterSpacing:1.2},title:{color:colors.textPrimary,fontSize:34,fontWeight:'900',marginTop:2},tagline:{color:colors.textSecondary,fontSize:17,lineHeight:25,marginTop:spacing.md},privacy:{marginTop:spacing.lg,padding:spacing.md,borderRadius:radius.lg,backgroundColor:colors.surfaceMuted,flexDirection:'row',gap:spacing.sm},privacyCopy:{flex:1,minWidth:0},privacyTitle:{color:colors.textPrimary,fontWeight:'900'},privacyText:{color:colors.textSecondary,fontSize:13,lineHeight:20,marginTop:spacing.xs},card:{marginTop:spacing.lg,padding:spacing.lg,borderRadius:radius.lg,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},section:{color:colors.textPrimary,fontSize:19,fontWeight:'900',marginBottom:spacing.sm},row:{minHeight:48,flexDirection:'row',alignItems:'center',gap:spacing.sm},rowText:{color:colors.textSecondary,fontSize:14,flex:1},architecture:{color:colors.textSecondary,fontSize:13,lineHeight:22},version:{color:colors.textMuted,textAlign:'center',fontSize:12,marginTop:spacing.lg},license:{color:colors.textMuted,textAlign:'center',fontSize:12,lineHeight:18,marginTop:spacing.sm}})}
