import { useMemo } from 'react';
import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import Constants from 'expo-constants';
import { router } from 'expo-router';
import { useAppPreferences } from '../src/app/AppPreferences';
import { AppIcon } from '../src/ui/AppIcon';
import { AppIconButton } from '../src/ui/AppSurface';
import { control, border, layout, radius, spacing, typography, type ThemeAccents, type ThemeColors } from '../src/theme';

export default function AboutScreen(){
 const {colors,accents,language}=useAppPreferences(); const bn=language==='bn'; const styles=useMemo(()=>makeStyles(colors,accents),[colors,accents]);
 const copy=bn?{back:'আরও',eyebrow:'OFFLINE MEMORY',title:'আমাদের সম্পর্কে',tagline:'ব্যক্তিগত স্মৃতি ও কাজ—আপনার ডিভাইসেই।',privacy:'Privacy-first · Offline-first',privacyText:'মূল টাস্ক, মেমোরি, সার্চ, পরিকল্পনা, NLP, রিমাইন্ডার এবং ব্যাকআপ লোকাল ডিভাইসে কাজ করে। আপনার ডেটা কোনো সার্ভারে পাঠানো হয় না, যদি না আপনি নিজে ব্যাকআপ শেয়ার করেন।',features:'মূল বৈশিষ্ট্য',items:['বাংলা ও English','Light ও Dark theme','লোকাল SQLite storage','লোকাল NLP ও Assistant','লোকাল reminders','Attachment-aware backup','ছবি, ভিডিও, PDF ও অন্যান্য ফাইল'],version:'Version',architecture:'Architecture',architectureText:'UI → Application Services → Local NLP/Assistant → Repository → SQLite → Notifications',license:'Offline Memory is a private, offline-first productivity application.','done':'সম্পন্ন'}:{back:'More',eyebrow:'OFFLINE MEMORY',title:'About',tagline:'Personal memory and work—kept on your device.',privacy:'Privacy-first · Offline-first',privacyText:'Core tasks, memories, search, planning, NLP, reminders and backups operate locally. Your data is not sent to a server unless you explicitly share a backup.',features:'Core capabilities',items:['Bangla and English','Light and Dark themes','Local SQLite storage','Local NLP and Assistant','Local reminders','Attachment-aware backups','Images, videos, PDFs and other files'],version:'Version',architecture:'Architecture',architectureText:'UI → Application Services → Local NLP/Assistant → Repository → SQLite → Notifications',license:'Offline Memory is a private, offline-first productivity application.','done':'Done'};
 return <ScrollView style={styles.container} contentContainerStyle={styles.content}><View style={styles.header}><AppIconButton icon="arrow-left" label={copy.back} variant="neutral" onPress={()=>router.back()}/><View style={styles.brand}><View style={styles.brandIcon}><AppIcon name="brain" size={control.iconSize} color={colors.onPrimary}/></View><View style={styles.brandCopy}><Text style={styles.eyebrow}>{copy.eyebrow}</Text><Text style={styles.title}>{copy.title}</Text></View></View><Text style={styles.tagline}>{copy.tagline}</Text><View style={styles.privacy}><AppIcon name="shield-lock-outline" size={control.iconSize} color={colors.success}/><View style={styles.privacyCopy}><Text style={styles.privacyTitle}>{copy.privacy}</Text><Text style={styles.privacyText}>{copy.privacyText}</Text></View></View></View><View style={styles.card}><Text style={styles.section}>{copy.features}</Text>{copy.items.map(item=><View key={item} style={styles.row}><AppIcon name="check-circle-outline" size={control.iconSize} color={colors.success}/><Text style={styles.rowText}>{item}</Text></View>)}</View><View style={styles.card}><Text style={styles.section}>{copy.architecture}</Text><Text style={styles.architecture}>{copy.architectureText}</Text></View><View style={styles.creditsCard}><View style={styles.creditsBadge}><AppIcon name="brain" size={control.iconSize} color={colors.onPrimary}/></View><Text style={styles.creditsApp}>Offline Memory</Text><Text style={styles.creditsVersion}>{copy.version} {Constants.expoConfig?.version ?? '0.1.0'}</Text><View style={styles.creditsRow}><Text style={styles.creditsMuted}>{bn?'ডেভেলপ করেছেন ':'Developed by '}</Text><Pressable accessibilityRole="link" accessibilityLabel="SUMON" hitSlop={8} onPress={()=>void Linking.openURL('https://mumainsumon.netlify.app').catch(()=>{})}><Text style={styles.creditsLink}>SUMON</Text></Pressable></View><View style={styles.creditsRow}><Text style={styles.creditsMuted}>Powered by </Text><Pressable accessibilityRole="link" accessibilityLabel="ABO ENTERPRISE" hitSlop={8} onPress={()=>void Linking.openURL('https://www.aboenterprise.com').catch(()=>{})}><Text style={styles.creditsLink}>ABO ENTERPRISE</Text></Pressable></View><Text style={styles.license}>{copy.license}</Text></View></ScrollView>;
}
function makeStyles(colors:ThemeColors,accents:ThemeAccents){return StyleSheet.create({container:{flex:1,backgroundColor:colors.background},content:{width:'100%',maxWidth:layout.contentMaxWidth,alignSelf:'center',paddingHorizontal:spacing.lg,paddingTop:spacing.md,paddingBottom:spacing.xxl},header:{paddingTop:spacing.sm},brand:{flexDirection:'row',alignItems:'center',gap:spacing.md,marginTop:spacing.lg},brandIcon:{width:control.titleIconSize,height:control.titleIconSize,borderRadius:radius.lg,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},brandCopy:{flex:1,minWidth:0},eyebrow:{color:colors.primary,...typography.label,fontWeight:'900',letterSpacing:0.8},title:{color:colors.textPrimary,...typography.titleLarge,fontWeight:'900',marginTop:spacing.xxs},tagline:{color:colors.textSecondary,...typography.body,marginTop:spacing.md},privacy:{marginTop:spacing.lg,padding:spacing.md,borderRadius:radius.lg,backgroundColor:accents.green.soft,borderWidth:border.thin,borderColor:accents.green.border,flexDirection:'row',gap:spacing.sm},privacyCopy:{flex:1,minWidth:0},privacyTitle:{color:colors.textPrimary,fontWeight:'900'},privacyText:{color:colors.textSecondary,...typography.meta,marginTop:spacing.xs},card:{marginTop:spacing.lg,padding:spacing.lg,borderRadius:radius.lg,backgroundColor:colors.surface,borderWidth:border.thin,borderColor:colors.border},section:{color:colors.textPrimary,...typography.cardTitle,fontWeight:'900',marginBottom:spacing.sm},row:{minHeight:layout.minTouchTarget,flexDirection:'row',alignItems:'center',gap:spacing.sm},rowText:{color:colors.textSecondary,...typography.bodySmall,flex:1},architecture:{color:colors.textSecondary,...typography.meta},version:{color:colors.textMuted,textAlign:'center',...typography.label,marginTop:spacing.lg},creditsCard:{marginTop:spacing.xl,padding:spacing.lg,borderRadius:radius.lg,backgroundColor:colors.surfaceMuted,borderWidth:border.thin,borderColor:colors.border,alignItems:'center',gap:spacing.xs},creditsBadge:{width:control.smallIconContainer,height:control.smallIconContainer,borderRadius:radius.md,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center',marginBottom:spacing.xxs},creditsApp:{color:colors.textPrimary,...typography.cardTitle},creditsVersion:{color:colors.textSecondary,...typography.caption,fontFamily:typography.numeric.fontFamily,marginBottom:spacing.xs},creditsRow:{flexDirection:'row',alignItems:'center',flexWrap:'wrap',justifyContent:'center'},creditsMuted:{color:colors.textMuted,...typography.caption},creditsLink:{color:colors.primary,...typography.caption,fontFamily:typography.label.fontFamily,textDecorationLine:'underline'},license:{color:colors.textMuted,textAlign:'center',...typography.caption,marginTop:spacing.sm}})}
