import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { Link } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { planInboxTasks } from '../src/services/planning-service';
import { useTaskStore } from '../src/store/task.store';
import { useAppPreferences } from '../src/app/AppPreferences';
import { AppCard, AppState } from '../src/ui/AppSurface';
import { AppIcon } from '../src/ui/AppIcon';
import { spacing, typography, type ThemeColors } from '../src/theme';
import type { Task, TaskPriority } from '../src/types/task-model';

const PRIORITY_LABELS:Record<TaskPriority,{en:string;bn:string}>={LOW:{en:'Low',bn:'কম'},MEDIUM:{en:'Medium',bn:'মাঝারি'},HIGH:{en:'High',bn:'উচ্চ'},URGENT:{en:'Urgent',bn:'জরুরি'}};
const priorityColor=(priority:TaskPriority,colors:ThemeColors)=>priority==='URGENT'?colors.danger:priority==='HIGH'?colors.warning:priority==='LOW'?colors.textMuted:colors.primary;

export default function InboxScreen(){const db=useSQLiteContext();const{colors,language}=useAppPreferences();const bn=language==='bn';const styles=useMemo(()=>makeStyles(colors),[colors]);const{tasks,isLoading,error,load}=useTaskStore();const[busyId,setBusyId]=useState<string|null>(null);const[mutationError,setMutationError]=useState(false);useEffect(()=>{void load(db)},[db,load]);const inbox=useMemo(()=>tasks.filter(task=>task.status==='INBOX'),[tasks]);const planTask=useCallback(async(id:string)=>{if(busyId)return;setBusyId(id);setMutationError(false);try{await planInboxTasks(db,[id]);await load(db)}catch{setMutationError(true)}finally{setBusyId(null)}},[busyId,db,load]);const copy=bn?{back:'হোম',eyebrow:'ক্যাপচার',title:'ইনবক্স',subtitle:'ক্যাপচার করা কিন্তু এখনও পরিকল্পনা না করা টাস্কগুলো এখানে থাকে।',clear:'আপনার ইনবক্স পরিষ্কার।',clearText:'নতুন কিছু ক্যাপচার করলে এখানে দেখা যাবে।',plan:'প্ল্যান',retry:'আবার চেষ্টা করুন',failed:'টাস্ক প্ল্যান করা যায়নি।'}:{back:'Home',eyebrow:'CAPTURE',title:'Inbox',subtitle:'Tasks you captured but have not planned yet.',clear:'Your inbox is clear.',clearText:'New captured tasks will appear here.',plan:'Plan',retry:'Retry',failed:'The task could not be planned.'};return <View style={styles.container}><View style={styles.header}><Link href="/" asChild><Pressable accessibilityRole="button" accessibilityLabel={copy.back} style={({pressed})=>[styles.back,pressed&&styles.pressed]}><AppIcon name="arrow-left" size={20} color={colors.primary}/><Text style={styles.backText}>{copy.back}</Text></Pressable></Link><View style={styles.titleRow}><View style={styles.titleIcon}><AppIcon name="inbox-arrow-down-outline" size={25} color={colors.primary}/></View><View style={styles.titleCopy}><Text style={styles.eyebrow}>{copy.eyebrow}</Text><Text style={styles.title}>{copy.title}</Text></View><View style={styles.count} accessibilityLabel={`${inbox.length} ${bn?'টাস্ক':'tasks'}`}><Text style={styles.countText}>{inbox.length}</Text></View></View><Text style={styles.subtitle}>{copy.subtitle}</Text></View>{error?<AppState title={bn?'ইনবক্স লোড করা যায়নি':'Could not load inbox'} description={bn?'ডেটা লোড করতে আবার চেষ্টা করুন।':'Unable to load local inbox data.'} icon="alert-circle-outline" actionLabel={copy.retry} onAction={()=>void load(db)}/>:null}{mutationError?<AppState title={bn?'প্ল্যান করা যায়নি':'Planning failed'} description={copy.failed} icon="alert-circle-outline" actionLabel={copy.retry} onAction={()=>void load(db)}/>:null}<FlatList data={inbox} keyExtractor={item=>item.id} contentContainerStyle={inbox.length?styles.list:styles.emptyList} ListEmptyComponent={isLoading?<AppState loading title={bn?'ইনবক্স লোড হচ্ছে…':'Loading inbox…'}/>:error?null:<AppState icon="inbox-check-outline" title={copy.clear} description={copy.clearText}/>} renderItem={({item})=><InboxRow task={item} busy={busyId===item.id} onPlan={()=>void planTask(item.id)} colors={colors} styles={styles} planLabel={copy.plan} bn={bn}/>}/></View>}
function InboxRow({task,busy,onPlan,colors,styles,planLabel,bn}:{task:Task;busy:boolean;onPlan:()=>void;colors:ThemeColors;styles:ReturnType<typeof makeStyles>;planLabel:string;bn:boolean}){const priority=PRIORITY_LABELS[task.priority];return <AppCard style={styles.row}><Link href={{pathname:'/task-editor',params:{id:task.id}}} asChild><Pressable accessibilityRole="button" accessibilityLabel={`${bn?'টাস্ক খুলুন':'Open task'}: ${task.title}`} style={({pressed})=>[styles.body,pressed&&styles.pressed]}><View style={styles.taskIcon}><AppIcon name="clipboard-text-outline" size={20} color={colors.primary}/></View><View style={styles.taskCopy}><Text numberOfLines={3} style={styles.task}>{task.title}</Text><Text style={[styles.meta,{color:priorityColor(task.priority,colors)}]}>{bn?priority.bn:priority.en}</Text></View><AppIcon name="chevron-right" size={20} color={colors.textMuted}/></Pressable></Link><Pressable disabled={busy} onPress={onPlan} accessibilityRole="button" accessibilityState={{busy,disabled:busy}} accessibilityLabel={`${planLabel} ${task.title}`} style={({pressed})=>[styles.planButton,busy&&styles.disabled,pressed&&styles.pressed]}>{busy?<ActivityIndicator color={colors.onPrimary}/>:<><AppIcon name="calendar-check-outline" size={17} color={colors.onPrimary}/><Text style={styles.planText}>{planLabel}</Text></>}</Pressable></AppCard>}
function makeStyles(colors:ThemeColors){return StyleSheet.create({container:{flex:1,backgroundColor:colors.background},header:{paddingHorizontal:spacing.lg,paddingTop:spacing.md,paddingBottom:spacing.lg},back:{minHeight:44,flexDirection:'row',alignItems:'center',gap:4,marginBottom:spacing.lg},backText:{color:colors.primary,fontSize:16,fontWeight:'800'},titleRow:{flexDirection:'row',alignItems:'center',gap:spacing.md},titleIcon:{width:50,height:50,borderRadius:16,backgroundColor:colors.surfaceMuted,alignItems:'center',justifyContent:'center'},titleCopy:{flex:1,minWidth:0},eyebrow:{color:colors.primary,fontSize:typography.label.fontSize,fontWeight:'900',letterSpacing:1.2},title:{color:colors.textPrimary,fontSize:34,fontWeight:'900',marginTop:2},count:{minWidth:34,height:34,borderRadius:17,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center',paddingHorizontal:8},countText:{color:colors.onPrimary,fontWeight:'900'},subtitle:{color:colors.textSecondary,fontSize:15,lineHeight:22,marginTop:spacing.md},list:{paddingHorizontal:spacing.lg,paddingBottom:spacing.xl,gap:spacing.sm},emptyList:{flexGrow:1,paddingHorizontal:spacing.lg},row:{flexDirection:'row',alignItems:'center',gap:spacing.sm,padding:spacing.sm},body:{flex:1,minWidth:0,minHeight:52,flexDirection:'row',alignItems:'center',gap:spacing.sm,paddingHorizontal:4},taskIcon:{width:40,height:40,borderRadius:12,backgroundColor:colors.surfaceMuted,alignItems:'center',justifyContent:'center'},taskCopy:{flex:1,minWidth:0},task:{color:colors.textPrimary,fontSize:15,fontWeight:'700'},meta:{fontSize:11,marginTop:4,fontWeight:'800'},planButton:{minHeight:44,minWidth:78,maxWidth:120,paddingHorizontal:spacing.sm,borderRadius:12,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:3},planText:{color:colors.onPrimary,fontWeight:'800',flexShrink:1},pressed:{opacity:.82},disabled:{opacity:.5}})}
