import { Link } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useMemo } from 'react';
import { useAppPreferences } from '../src/app/AppPreferences';
import { more } from '../src/i18n/more';
import { AppIcon } from '../src/ui/AppIcon';
import { elevation, layout, radius, spacing, typography, type ThemeColors } from '../src/theme';

const groups=[
 {key:'Tools',items:[{href:'/search' as const,icon:'magnify' as const,copyKey:'search'},{href:'/assistant' as const,icon:'robot-outline' as const,copyKey:'assistant'}]},
 {key:'Data',items:[{href:'/backup' as const,icon:'database-export-outline' as const,copyKey:'backup'}]},
 {key:'Notifications',items:[{href:'/reminders' as const,icon:'bell-outline' as const,copyKey:'reminders'}]},
 {key:'System',items:[{href:'/diagnostics' as const,icon:'heart-pulse' as const,copyKey:'diagnostics'},{href:'/settings' as const,icon:'cog-outline' as const,copyKey:'settings'},{href:'/about' as const,icon:'information-outline' as const,copyKey:'about'}]},
] as const;
type GroupCopy={title:string;items:Record<string,{title:string;description:string}>};
export default function MoreScreen(){const{language,colors}=useAppPreferences();const copy=more(language);const styles=useMemo(()=>makeStyles(colors),[colors]);return <ScrollView style={styles.container} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.header}><Link href="/" asChild><Pressable accessibilityRole="button" accessibilityLabel={copy.back} style={({pressed})=>StyleSheet.flatten([styles.back,pressed&&styles.pressed])}><AppIcon name="arrow-left" size={20} color={colors.primary}/><Text style={styles.backText}>{copy.back}</Text></Pressable></Link><Text style={styles.eyebrow}>{copy.eyebrow}</Text><Text style={styles.title}>{copy.title}</Text><Text style={styles.subtitle}>{copy.subtitle}</Text></View>{groups.map(group=>{const groupCopy=copy.groups[group.key] as GroupCopy;return <View key={group.key} style={styles.group}><Text style={styles.section}>{groupCopy.title}</Text><View style={styles.list}>{group.items.map(item=>{const itemCopy=groupCopy.items[item.copyKey];return <Link key={item.href} href={item.href} asChild><Pressable accessibilityRole="button" accessibilityLabel={itemCopy.title} style={({pressed})=>StyleSheet.flatten([styles.card,pressed&&styles.pressed])}><View style={styles.iconWrap}><AppIcon name={item.icon} size={23} color={colors.primary}/></View><View style={styles.copy}><Text style={styles.cardTitle}>{itemCopy.title}</Text><Text style={styles.cardDescription}>{itemCopy.description}</Text></View><AppIcon name="chevron-right" size={22} color={colors.textMuted}/></Pressable></Link>})}</View></View>})}</ScrollView>}
function makeStyles(colors:ThemeColors){return StyleSheet.create({container:{flex:1,backgroundColor:colors.background},content:{width:'100%',maxWidth:layout.contentMaxWidth,alignSelf:'center',paddingHorizontal:spacing.lg,paddingTop:spacing.md,paddingBottom:spacing.xxl},header:{paddingTop:spacing.sm,marginBottom:spacing.lg},back:{minHeight:layout.minTouchTarget,flexDirection:'row',alignItems:'center',gap:spacing.xs,marginBottom:spacing.md},backText:{color:colors.primary,fontSize:16,fontWeight:'800'},eyebrow:{color:colors.primary,fontSize:typography.label.fontSize,fontWeight:'900',letterSpacing:1.2},title:{color:colors.textPrimary,fontSize:36,fontWeight:'900',marginTop:spacing.sm},subtitle:{color:colors.textSecondary,fontSize:15,lineHeight:22,marginTop:spacing.sm},group:{marginBottom:spacing.lg},section:{color:colors.textMuted,fontSize:11,fontWeight:'900',letterSpacing:1.2,marginBottom:spacing.sm},list:{gap:spacing.sm},card:{minHeight:88,flexDirection:'row',alignItems:'center',gap:spacing.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md,...elevation.card},iconWrap:{width:layout.iconButtonSize,height:layout.iconButtonSize,borderRadius:radius.md,backgroundColor:colors.surfaceMuted,alignItems:'center',justifyContent:'center'},copy:{flex:1,minWidth:0},cardTitle:{color:colors.textPrimary,fontSize:16,fontWeight:'800'},cardDescription:{color:colors.textSecondary,fontSize:13,lineHeight:19,marginTop:spacing.xs},pressed:{opacity:0.78}})}
