import { Link } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useMemo } from 'react';
import { useAppPreferences } from '../src/app/AppPreferences';
import { more } from '../src/i18n/more';
import { AppIcon } from '../src/ui/AppIcon';
import Constants from 'expo-constants';
import { border, control, elevation, icon as iconToken, layout, radius, spacing, typography, type AccentName, type ThemeColors } from '../src/theme';

const groups=[
 {key:'Tools',accent:'blue' as AccentName,items:[{href:'/search' as const,icon:'magnify' as const,copyKey:'search'},{href:'/assistant' as const,icon:'robot-happy-outline' as const,copyKey:'assistant'}]},
 {key:'Data',accent:'green' as AccentName,items:[{href:'/backup' as const,icon:'database-lock-outline' as const,copyKey:'backup'}]},
 {key:'Notifications',accent:'yellow' as AccentName,items:[{href:'/reminders' as const,icon:'bell-outline' as const,copyKey:'reminders'}]},
 {key:'System',accent:'purple' as AccentName,items:[{href:'/diagnostics' as const,icon:'heart-pulse' as const,copyKey:'diagnostics'},{href:'/settings' as const,icon:'cog-outline' as const,copyKey:'settings'},{href:'/about' as const,icon:'information-outline' as const,copyKey:'about'}]},
] as const;
type GroupCopy={title:string;items:Record<string,{title:string;description:string}>};
export default function MoreScreen(){const{language,colors,accents}=useAppPreferences();const copy=more(language);const styles=useMemo(()=>makeStyles(colors),[colors]);const bn=language==='bn';return <ScrollView style={styles.container} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.header}><Text style={styles.eyebrow}>{copy.eyebrow}</Text><Text style={styles.title}>{copy.title}</Text><Text style={styles.subtitle}>{copy.subtitle}</Text></View><View style={styles.brandCard}><View style={styles.brandBadge}><Text style={styles.brandBadgeText}>PA</Text></View><View style={styles.brandCopy}><Text style={styles.brandName}>{bn?'পার্সোনাল অ্যাসিস্ট্যান্ট':'Personal Assistant'}</Text><Text style={styles.brandMeta}>{bn?'সংস্করণ':'Version'} {Constants.expoConfig?.version ?? '0.1.0'} · {bn?'১০০% অফলাইন':'100% offline'}</Text></View></View>{groups.map(group=>{const groupCopy=copy.groups[group.key] as GroupCopy;const tone=accents[group.accent];return <View key={group.key} style={styles.group}><View style={styles.sectionRow}><View style={[styles.sectionDot,{backgroundColor:tone.base}]}/><Text style={styles.section}>{groupCopy.title}</Text></View><View style={styles.grid}>{group.items.map(item=>{const itemCopy=groupCopy.items[item.copyKey]!;return <Link key={item.href} href={item.href} asChild><Pressable accessibilityRole="button" accessibilityLabel={itemCopy.title} style={({pressed})=>StyleSheet.flatten([styles.tile,group.items.length===1&&styles.tileWide,pressed&&styles.pressed])}><View style={[styles.iconWrap,{backgroundColor:tone.soft}]}><AppIcon name={item.icon} size={iconToken.md} color={tone.on}/></View><Text numberOfLines={1} style={styles.tileTitle}>{itemCopy.title}</Text><Text numberOfLines={2} style={styles.tileDesc}>{itemCopy.description}</Text></Pressable></Link>})}</View></View>})}</ScrollView>}
function makeStyles(colors:ThemeColors){return StyleSheet.create({container:{flex:1,backgroundColor:colors.background},content:{width:'100%',maxWidth:layout.contentMaxWidth,alignSelf:'center',paddingHorizontal:spacing.lg,paddingTop:spacing.md,paddingBottom:spacing.xxl},header:{paddingTop:spacing.md,marginBottom:spacing.md},eyebrow:{color:colors.primary,...typography.label,letterSpacing:0.8},title:{color:colors.textPrimary,...typography.display,marginTop:spacing.sm},subtitle:{color:colors.textSecondary,...typography.input,marginTop:spacing.sm},brandCard:{flexDirection:'row',alignItems:'center',gap:spacing.md,backgroundColor:colors.surface,borderWidth:border.thin,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md,marginBottom:spacing.lg,...elevation.soft},brandBadge:{width:control.smallIconContainer,height:control.smallIconContainer,borderRadius:radius.md,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},brandBadgeText:{color:colors.onPrimary,...typography.cardTitle,fontFamily:typography.numeric.fontFamily},brandCopy:{flex:1,minWidth:0},brandName:{color:colors.textPrimary,...typography.body,fontFamily:typography.cardTitle.fontFamily},brandMeta:{color:colors.textMuted,...typography.caption,marginTop:spacing.xxs},group:{marginBottom:spacing.lg},sectionRow:{flexDirection:'row',alignItems:'center',gap:spacing.xs,marginBottom:spacing.sm},sectionDot:{width:6,height:6,borderRadius:radius.pill},section:{color:colors.textMuted,...typography.section,letterSpacing:1},grid:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},tile:{width:'47.6%',flexGrow:1,minHeight:118,backgroundColor:colors.surface,borderWidth:border.thin,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md,gap:spacing.xs,...elevation.soft},tileWide:{width:'100%'},iconWrap:{width:control.smallIconContainer,height:control.smallIconContainer,borderRadius:radius.md,alignItems:'center',justifyContent:'center',marginBottom:spacing.xxs},tileTitle:{color:colors.textPrimary,...typography.body,fontFamily:typography.cardTitle.fontFamily},tileDesc:{color:colors.textSecondary,...typography.caption,lineHeight:17},pressed:{opacity:0.78}})}
